const SCRIPT = `(()=>{if(!['/accelstretch','/secure-checkout'].includes(location.pathname))return;const A='https://api.flexiblest.io/api/web-vitals',q=new URLSearchParams(location.search),st=(()=>{try{return JSON.parse(localStorage.getItem('fs_attribution_data')||'{}')}catch(e){return{}}})(),u=navigator.userAgent||'',r=(q.get('utm_source')||q.get('site_source_name')||q.get('comet_source')||st.utm_source||st.site_source_name||st.comet_source||document.referrer||'').toLowerCase(),src=/instagram/.test(r+u)?'instagram':/facebook|fbav|fban/.test(r+u)?'facebook':/meta/.test(r)?'meta':r?'other':'direct',d=innerWidth<768?'mobile':innerWidth<992?'tablet':'desktop',n=performance.getEntriesByType('navigation')[0],send=(m,v)=>{if(v==null||!isFinite(v))return;let b=JSON.stringify({metric:m,value:v,path:location.pathname,device:d,source:src,inApp:/FBAN|FBAV|Instagram/i.test(u),navigationType:n?.type||'',viewportWidth:innerWidth});try{if(navigator.sendBeacon&&navigator.sendBeacon(A,new Blob([b],{type:'text/plain'})))return}catch(e){}fetch(A,{method:'POST',headers:{'Content-Type':'text/plain'},body:b,keepalive:true}).catch(()=>{})};let l=0,c=0,i=0,z=0;try{new PerformanceObserver(x=>{let e=x.getEntries().at(-1);if(e)l=e.startTime}).observe({type:'largest-contentful-paint',buffered:true})}catch(e){}try{new PerformanceObserver(x=>x.getEntries().forEach(e=>{if(!e.hadRecentInput)c+=e.value})).observe({type:'layout-shift',buffered:true})}catch(e){}try{new PerformanceObserver(x=>x.getEntries().forEach(e=>{if(e.interactionId)i=Math.max(i,e.duration)})).observe({type:'event',buffered:true,durationThreshold:40})}catch(e){}try{new PerformanceObserver(x=>x.getEntries().forEach(e=>{if(e.name==='first-contentful-paint')send('FCP',e.startTime)})).observe({type:'paint',buffered:true})}catch(e){}if(n)send('TTFB',n.responseStart);const f=()=>{if(z)return;z=1;if(l)send('LCP',l);send('CLS',c);if(i)send('INP',i)};addEventListener('pagehide',f);addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')f()});if(location.pathname==='/secure-checkout'){let a=0,b=0;const g=()=>{if(!document.querySelector('.fsu-paypro-frame.is-ready'))return;if(!a){a=1;send('IFRAME',performance.now())}if(b){send('BUMP',performance.now()-b);b=0}};new MutationObserver(g).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});addEventListener('click',e=>{if(e.target.closest('.bump-top-bar'))b=performance.now()},true);g()}})();`;

export default function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).end();
  }
  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=300, s-maxage=300');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  return res.status(200).send(SCRIPT);
}
